from typing import Protocol, List, Optional
from ..entities.cuaderno import Cuaderno
from ..entities.archivo import Archivo
from ..entities.chat import Chat, Mensaje
from ..entities.flashcard import Flashcard

class CuadernoRepository(Protocol):
    """
    Contrato de repositorio para el Cuaderno.
    """
    async def get_by_id(self, notebook_id: int) -> Optional[Cuaderno]: ...
    async def list_by_usuario_id(self, usuario_id: int) -> List[Cuaderno]: ...
    async def save(self, cuaderno: Cuaderno) -> None: ...
    async def delete(self, notebook_id: int) -> None: ...
    
    # Operaciones específicas de archivos y chats
    async def get_archivo_by_id(self, archivo_id: int) -> Optional[Archivo]: ...
    async def save_archivo(self, archivo: Archivo) -> None: ...
    async def delete_archivo(self, archivo_id: int) -> None: ...
    async def list_archivos_by_notebook_id(self, notebook_id: int) -> List[Archivo]: ...
    
    async def get_chat_by_id(self, chat_id: int) -> Optional[Chat]: ...
    async def save_chat(self, chat: Chat) -> None: ...
    async def delete_chat(self, chat_id: int) -> None: ...
    async def list_chats_by_notebook_id(self, notebook_id: int) -> List[Chat]: ...
    
    async def get_messages_paginated(self, chat_id: int, limit: int, offset: int) -> List[Mensaje]: ...
    async def save_message(self, message: Mensaje) -> None: ...
    
    async def save_flashcard(self, flashcard: Flashcard) -> None: ...
    async def list_flashcards_by_notebook_id(self, notebook_id: int) -> List[Flashcard]: ...
