import asyncio
from typing import Protocol
from ..usuario import Usuario

class UsuarioRepository(Protocol):
    async def get_usuario_by_email(self, email:str) -> Usuario | None: ...
    async def get_usuario_by_id(self, usuario_id: int) -> Usuario | None: ...
    async def save_usuario(self, usuario: Usuario) -> None: ...
    async def delete_usuario(self, usuario_id: int) -> None: ...