import asyncio
from typing import Protocol

class EncryptService(Protocol):
    async def hash_password(self, password: str) -> str: ...
    async def compare_password(self, password: str, hashed_password:str) -> bool: ...