from typing import Protocol, List, Optional
from ..entities.examen import Examen, IntentoExamen

class ExamenRepository(Protocol):
    """
    Contrato de repositorio para exámenes, preguntas e intentos privados.
    """
    async def get_examen_by_id(self, examen_id: int) -> Optional[Examen]: ...
    async def list_examenes_by_notebook_id(self, notebook_id: int) -> List[Examen]: ...
    async def list_examenes_by_sala_id(self, sala_id: int) -> List[Examen]: ...
    async def save_examen(self, examen: Examen) -> None: ...
    async def delete_examen(self, examen_id: int) -> None: ...

    async def get_intento_by_id(self, intento_id: int) -> Optional[IntentoExamen]: ...
    async def list_intentos_by_usuario_id(self, usuario_id: int) -> List[IntentoExamen]: ...
    async def list_intentos_by_examen_id(self, examen_id: int) -> List[IntentoExamen]: ...
    async def save_intento(self, intento: IntentoExamen) -> None: ...
