from typing import Protocol, List, Optional
from ..entities.sala_estudio import SalaEstudio, ParticipanteSala

class SalaEstudioRepository(Protocol):
    """
    Contrato de repositorio para gestionar salas de estudio colaborativas.
    """
    async def get_by_id(self, sala_id: int) -> Optional[SalaEstudio]: ...
    async def get_by_codigo(self, codigo: str) -> Optional[SalaEstudio]: ...
    async def list_by_usuario_id(self, usuario_id: int) -> List[SalaEstudio]: ...
    async def list_by_participante_id(self, usuario_id: int) -> List[SalaEstudio]: ...
    async def save(self, sala: SalaEstudio) -> None: ...
    async def delete(self, sala_id: int) -> None: ...
    
    # Participantes
    async def get_participante(self, sala_id: int, usuario_id: int) -> Optional[ParticipanteSala]: ...
    async def save_participante(self, participante: ParticipanteSala) -> None: ...
    async def delete_participante(self, sala_id: int, usuario_id: int) -> None: ...
    async def list_participantes(self, sala_id: int) -> List[ParticipanteSala]: ...
